trigger:
- main
- Dev
- Qa

pr:
- main
- Dev
- Qa

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Instalar .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '9.x'

- script: dotnet restore
  displayName: 'Restaurar dependencias'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Compilar proyecto'

- task: DotNetCoreCLI@2
  displayName: 'Ejecutar pruebas unitarias'
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --collect:"XPlat Code Coverage"'

- task: PublishTestResults@2
  displayName: 'Publicar resultados de pruebas'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
